// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type BuyRecordEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	BuyNumber	int	`gorm:"column:BuyNumber"`
	Type	int	`gorm:"column:Type"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Spend	float64	`gorm:"column:Spend"`
	CustomerId	string	`gorm:"column:CustomerId"`
	Id	string	`gorm:"column:Id"`
	Name	string	`gorm:"column:Name"`
	ProjectId	string	`gorm:"column:ProjectId"`
	SalesMan	string	`gorm:"column:SalesMan"`
	DepartmentId	string	`gorm:"column:DepartmentId"`
	DepartmentName	string	`gorm:"column:DepartmentName"`
	EmpeeId	string	`gorm:"column:EmpeeId"`
	Mobile	string	`gorm:"column:Mobile"`
	OrderId	string	`gorm:"column:OrderId"`
}

// TableName 表名
func (*BuyRecordEntity) TableName() string {
    return "BuyRecordEntity"
}