// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type CureEntity struct {
	CreateTime	time.Time	`gorm:"column:createTime"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Money	float64	`gorm:"column:Money"`
	Name	string	`gorm:"column:Name"`
	Id	string	`gorm:"column:Id"`
	DepartmentId	string	`gorm:"column:DepartmentId"`
}

// TableName 表名
func (*CureEntity) TableName() string {
    return "CureEntity"
}