// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type CustomerEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	Age	int	`gorm:"column:Age"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagAway	bool	`gorm:"column:FlagAway"`
	SpendMoney	float64	`gorm:"column:SpendMoney"`
	Name	string	`gorm:"column:Name"`
	Mobile	string	`gorm:"column:Mobile"`
	SalesManName	string	`gorm:"column:SalesManName"`
	Id	string	`gorm:"column:Id"`
	Department	string	`gorm:"column:Department"`
	HeadPic	string	`gorm:"column:HeadPic"`
	ReceiveAddress	string	`gorm:"column:ReceiveAddress"`
	AwayReason	string	`gorm:"column:AwayReason"`
	HopeSolution	string	`gorm:"column:HopeSolution"`
	HopeIncream	string	`gorm:"column:HopeIncream"`
	SalesManId	string	`gorm:"column:SalesManId"`
}

// TableName 表名
func (*CustomerEntity) TableName() string {
    return "CustomerEntity"
}