// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type DepartmentEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	Limit	int	`gorm:"column:Limit"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Name	string	`gorm:"column:Name"`
	Id	string	`gorm:"column:Id"`
	Status	string	`gorm:"column:Status"`
}

// TableName 表名
func (*DepartmentEntity) TableName() string {
    return "DepartmentEntity"
}