// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type FirstBuyEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	Id	int	`gorm:"column:Id"`
	CustomerId	int	`gorm:"column:CustomerId"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagYa	bool	`gorm:"column:FlagYa"`
	FlagFirstMonthPicture	bool	`gorm:"column:FlagFirstMonthPicture"`
	FlagFirstMonthChange	bool	`gorm:"column:FlagFirstMonthChange"`
	FlagReturn	bool	`gorm:"column:FlagReturn"`
	FlagUsedOther	bool	`gorm:"column:FlagUsedOther"`
	UsedHabit	string	`gorm:"column:UsedHabit"`
	EmpId	string	`gorm:"column:EmpId"`
	BodyStatus	string	`gorm:"column:BodyStatus"`
	SkinType	string	`gorm:"column:SkinType"`
	Wrinkle	string	`gorm:"column:Wrinkle"`
	Drink	string	`gorm:"column:Drink"`
	FoodLove	string	`gorm:"column:FoodLove"`
	Sleep	string	`gorm:"column:Sleep"`
	Work	string	`gorm:"column:Work"`
}

// TableName 表名
func (*FirstBuyEntity) TableName() string {
    return "FirstBuyEntity"
}