// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type FirstMonthEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagYa	bool	`gorm:"column:FlagYa"`
	FlagUsedNotOld	bool	`gorm:"column:FlagUsedNotOld"`
	FlagReturnHospital	bool	`gorm:"column:FlagReturnHospital"`
	FlagChange	bool	`gorm:"column:FlagChange"`
	Id	string	`gorm:"column:Id"`
	FirstPic	string	`gorm:"column:FirstPic"`
	Habit	string	`gorm:"column:Habit"`
	BodyStatus	string	`gorm:"column:BodyStatus"`
	SkinType	string	`gorm:"column:SkinType"`
	Wrinkle	string	`gorm:"column:Wrinkle"`
	WorkStatus	string	`gorm:"column:WorkStatus"`
	ChangeDetail	string	`gorm:"column:ChangeDetail"`
	EmpId	string	`gorm:"column:EmpId"`
	UsedHuFu	string	`gorm:"column:UsedHuFu"`
	UsedJieMian	string	`gorm:"column:UsedJieMian"`
	UsedHuaZhuang	string	`gorm:"column:UsedHuaZhuang"`
	Drink	string	`gorm:"column:Drink"`
	FoodHabit	string	`gorm:"column:FoodHabit"`
	SleppStatus	string	`gorm:"column:SleppStatus"`
}

// TableName 表名
func (*FirstMonthEntity) TableName() string {
    return "FirstMonthEntity"
}