// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type HuiFangEntity struct {
	CreaTime	time.Time	`gorm:"column:CreaTime"`
	HuiFangTime	time.Time	`gorm:"column:HuiFangTime"`
	Id	int	`gorm:"column:Id"`
	BuyRecordId	int	`gorm:"column:BuyRecordId"`
	DepartmentId	int	`gorm:"column:DepartmentId"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagHuiFang	bool	`gorm:"column:FlagHuiFang"`
	HuiFangType	string	`gorm:"column:HuiFangType"`
	HuiFangCustomerMobile	string	`gorm:"column:HuiFangCustomerMobile"`
	HuiFangEmpeeId	string	`gorm:"column:HuiFangEmpeeId"`
	HuiFangCustomerName	string	`gorm:"column:HuiFangCustomerName"`
}

// TableName 表名
func (*HuiFangEntity) TableName() string {
    return "HuiFangEntity"
}