// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type ProjectEntity struct {
	CreateTime	time.Time	`gorm:"column:createTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Money	float64	`gorm:"column:Money"`
	Name	string	`gorm:"column:Name"`
	Id	string	`gorm:"column:Id"`
	UpdatePerson	string	`gorm:"column:UpdatePerson"`
	DepartmentId	string	`gorm:"column:DepartmentId"`
}

// TableName 表名
func (*ProjectEntity) TableName() string {
    return "ProjectEntity"
}