// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type SalesManEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Mobile	string	`gorm:"column:Mobile"`
	DepartmentId	string	`gorm:"column:DepartmentId"`
	Id	string	`gorm:"column:Id"`
	Name	string	`gorm:"column:Name"`
}

// TableName 表名
func (*SalesManEntity) TableName() string {
    return "SalesManEntity"
}