// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type SecondMonthEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	CustomerId	int	`gorm:"column:CustomerId"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagSkinFuSe	bool	`gorm:"column:FlagSkinFuSe"`
	FlagSkinGuangZe	bool	`gorm:"column:FlagSkinGuangZe"`
	FlagShengLi	bool	`gorm:"column:FlagShengLi"`
	FlagYanSe	bool	`gorm:"column:FlagYanSe"`
	FlagSeBan	bool	`gorm:"column:FlagSeBan"`
	FlagHair	bool	`gorm:"column:FlagHair"`
	FlagNextBuy	bool	`gorm:"column:FlagNextBuy"`
	FlagReturnHospital	bool	`gorm:"column:FlagReturnHospital"`
	FlagYa	bool	`gorm:"column:FlagYa"`
	Id	string	`gorm:"column:Id"`
	SecondRemind	string	`gorm:"column:SecondRemind"`
	DispleasureResson	string	`gorm:"column:DispleasureResson"`
	Solution	string	`gorm:"column:Solution"`
	Other	string	`gorm:"column:Other"`
	FangSaiFeel	string	`gorm:"column:FangSaiFeel"`
	EmpId	string	`gorm:"column:EmpId"`
	BodyStatus	string	`gorm:"column:BodyStatus"`
	FoodLove	string	`gorm:"column:FoodLove"`
	SkinType	string	`gorm:"column:SkinType"`
	Drink	string	`gorm:"column:Drink"`
	Wrinkle	string	`gorm:"column:Wrinkle"`
}

// TableName 表名
func (*SecondMonthEntity) TableName() string {
    return "SecondMonthEntity"
}