// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type TaskEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	TaskTime	time.Time	`gorm:"column:TaskTime"`
	Number	int	`gorm:"column:Number"`
	FactToal	int	`gorm:"column:FactToal"`
	FactMoney	string	`gorm:"column:FactMoney"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	Id	string	`gorm:"column:Id"`
	DepartmentId	string	`gorm:"column:DepartmentId"`
	DepartmentName	string	`gorm:"column:DepartmentName"`
	ProjectName	string	`gorm:"column:ProjectName"`
}

// TableName 表名
func (*TaskEntity) TableName() string {
    return "TaskEntity"
}