// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type ThirdMonthEntity struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	UpdateTime	time.Time	`gorm:"column:UpdateTime"`
	CustomerId	int	`gorm:"column:CustomerId"`
	FlagDelete	bool	`gorm:"column:FlagDelete"`
	FlagSkinXini	bool	`gorm:"column:FlagSkinXini"`
	FlagBan	bool	`gorm:"column:FlagBan"`
	FlagReturnHospital	bool	`gorm:"column:FlagReturnHospital"`
	FlagSkinHouDu	bool	`gorm:"column:FlagSkinHouDu"`
	FlagYeShi	bool	`gorm:"column:FlagYeShi"`
	FlagQuBan	bool	`gorm:"column:FlagQuBan"`
	FangSaiFeel	bool	`gorm:"column:FangSaiFeel"`
	FlagPingHuan	bool	`gorm:"column:FlagPingHuan"`
	FlagNextBuy	bool	`gorm:"column:FlagNextBuy"`
	FlagYa	bool	`gorm:"column:FlagYa"`
	Id	string	`gorm:"column:Id"`
	DispleasureResson	string	`gorm:"column:DispleasureResson"`
	Solution	string	`gorm:"column:Solution"`
	Other	string	`gorm:"column:Other"`
	EmpId	string	`gorm:"column:EmpId"`
	BodyStatus	string	`gorm:"column:BodyStatus"`
	Wrinkle	string	`gorm:"column:Wrinkle"`
	Drink	string	`gorm:"column:Drink"`
	FoodLove	string	`gorm:"column:FoodLove"`
	SkinType	string	`gorm:"column:SkinType"`
}

// TableName 表名
func (*ThirdMonthEntity) TableName() string {
    return "ThirdMonthEntity"
}