// Package model_temp This file is generated by Cli, please do not modify
package model_temp


import "time"


type UpdateRecord struct {
	CreateTime	time.Time	`gorm:"column:CreateTime"`
	Id	string	`gorm:"column:Id"`
	EmpId	string	`gorm:"column:EmpId"`
	CustomerId	string	`gorm:"column:CustomerId"`
	Change	string	`gorm:"column:Change"`
	FlagDelete	string	`gorm:"column:FlagDelete"`
}

// TableName 表名
func (*UpdateRecord) TableName() string {
    return "UpdateRecord"
}